name: Publish yaqd-seabreeze

on:
  release:
    types: [created]

jobs:

  build:
    name: Build release distribution 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"  
    - name: Install dependencies
      run: >-
        python -m pip install --upgrade pip
        pip install twine build setuptools
    - name: build
      run: >-
        python -m build
        twine check dist/*

  deploy:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/yaqd-seabreeze
    permissions:
      id-token: write
    steps:
    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
  
